[package]
name = "bitcoin_escrow_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.4"
ic-cdk-macros = "0.6.10"
ic-stable-structures = "0.5.4"
serde = { version = "1.0", features = ["derive"] } 